### PR TITLE
empty config should be invalid

### LINKED ISSUE #26: Empty slo-exporter configuration is declared as valid
## Problem

Empty main configuration file is according to config checker valid. This is incorrect.

## Reproducibility 100%
```sh
$ ./slo_exporter --version
slo_exporter version 6.4.0 (from commit 3c44f001e863265e588e319138e743bc682b70b3 at 2020-08-07T10:58:03Z by goreleaser)

$ touch /tmp/slo-exporter.yaml
✓ freznicek@localhost.localdomain /tmp

$ ./slo_exporter --config-file /tmp/slo-exporter.yaml --check-config
time="2020-08-07T16:23:38.01516+02:00" level=info msg="Configuration is valid!"
✓ freznicek@localhost.localdomain /tmp

$ ./slo_exporter --config-file /tmp/slo-exporter.yaml
time="2020-08-07T16:23:42.81021+02:00" level=warning msg="changing readiness status to not ok, reason: initializing" component=prober
...
time="2020-08-07T16:23:42.8119+02:00" level=info msg="changing readiness status to ok" component=prober
time="2020-08-07T16:23:43.81233+02:00" level=info msg="finished processing all logs"
time="2020-08-07T16:23:43.81245+02:00" level=info msg="gracefully shutting down"
time="2020-08-07T16:23:43.8125+02:00" level=warning msg="changing readiness status to not ok, reason: shutting down" component=prober
time="2020-08-07T16:23:43.81258+02:00" level=info msg="see you next time!"
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/seznam/slo-exporter/pkg/pipeline.(*Manager).StopPipeline(0xc00025e240, 0xe85e60, 0xc000316180, 0xe85e60)
        /home/circleci/project/pkg/pipeline/manager.go:69 +0xc1
main.main()
        /home/circleci/project/cmd/slo_exporter.go:224 +0x1365
```

### PR DESCRIPTION
**Pull request by freznicek**
## Why is this fix needed?

Resolves #26 

## Fix idea

Let Pipeline manager to throw an error when empty pipeline is getting started.
Normal error propagation used although panic could be an option as well.

### CODE REVIEW

**Comment by freznicek** [comment]
Tests need some more refactoring around this, will work it out once I'm back from holiday.
```go
m, err := newTestManager()
assert.NoError(t, err)

```

**Comment by lksv** [comment]
LGTM

**Review by david-vavra — APPROVED** [review]
lgtm

File: pkg/pipeline/manager.go [hunk 1]
```diff
@@ -53,16 +53,20 @@ type Manager struct {
 	logger   logrus.FieldLogger
 }
 
-func (m *Manager) StartPipeline() {
+func (m *Manager) StartPipeline() error {
 	m.logger.Info("starting pipeline... ")
+
+	if len(m.pipeline) == 0 {
```
Comment (FUSAKLA) [inline pkg/pipeline/manager.go:59]: I'm wondering if we could add the check already to the `NewManager` funciton, this way it would be checked even when using the `--check-config` flag to validate configuration. On the other hand maybe it's really just runtime issue and the configuration can be still validated :thinking:

Comment (freznicek) [reply pkg/pipeline/manager.go:59]: I was initially about to inject test into `NewManager()` but changed my mind as soon as found  `manager.addModuleToPipelineEnd(...)` method which makes following pattern legal (used in tests):

```go
manager, err := NewManager(...)
...
err = manager.addModuleToPipelineEnd(...)
...
```

This pattern forces me to add check in `manager.StartPipeline()` allowing `NewManager` pass even without pipelines specified. Does it make sense to you?

Comment (freznicek) [reply pkg/pipeline/manager.go:59]: I can see your point `./slo_exporter --config-file /tmp/empty-file.yaml --check-config` still claims even empty configuration is valid, will address that in additional PR.
